"""Static HTML preview of theme structure (not full Blogger runtime)."""

from __future__ import annotations

from html import escape
from pathlib import Path


def structure_to_preview_html(structure: dict) -> str:
    """Render a lightweight static HTML mock from a theme structure dict."""
    title = escape(str(structure.get("title") or "My Blog"))
    colors = structure.get("colors") or {}
    primary = escape(str(colors.get("primary") or "#1a73e8"))
    secondary = escape(str(colors.get("secondary") or "#34a853"))
    background = escape(str(colors.get("background") or "#ffffff"))
    text = escape(str(colors.get("text") or "#222222"))
    fonts = structure.get("fonts") or {}
    body_font = escape(str(fonts.get("body") or "system-ui, sans-serif"))
    heading_font = escape(str(fonts.get("heading") or "Georgia, serif"))
    layout = str(structure.get("layout") or "single-column")
    sidebar = bool((structure.get("features") or {}).get("sidebar")) or layout == "two-column"
    nav = structure.get("nav_links") or []
    nav_html = "".join(f'<a href="#">{escape(str(n.get("label") or "Link"))}</a>' for n in nav[:8])
    if not nav_html:
        nav_html = '<a href="#">Home</a><a href="#">About</a>'
    desc = escape(str(structure.get("description") or "Preview generated by BloggerEasy"))
    paras = structure.get("sample_paragraphs") or [
        "This is a static preview of your Blogger theme structure.",
        "Import the companion XML into Blogger Theme → Backup/Restore to go live.",
    ]
    body = "".join(f"<p>{escape(str(p))}</p>" for p in paras[:4])
    aside = ""
    if sidebar:
        aside = (
            f'<aside class="sidebar"><h3>Sidebar</h3>'
            f'<p style="color:{secondary}">Widgets &amp; labels appear here in Blogger.</p></aside>'
        )
    grid = "1fr 280px" if sidebar else "1fr"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>{title} · BloggerEasy preview</title>
  <style>
    body {{ margin:0; font-family:{body_font}; color:{text}; background:{background}; }}
    header {{ background:{primary}; color:#fff; padding:1.5rem 2rem; }}
    header h1 {{ font-family:{heading_font}; margin:0; }}
    nav {{ display:flex; gap:1rem; padding:0.75rem 2rem; background:{secondary}; }}
    nav a {{ color:#fff; text-decoration:none; font-weight:600; }}
    .wrap {{ display:grid; grid-template-columns:{grid}; gap:1.25rem; max-width:960px; margin:1.25rem auto; padding:0 1rem; }}
    main {{ background:rgba(0,0,0,0.03); border-radius:12px; padding:1.25rem; }}
    .sidebar {{ background:rgba(0,0,0,0.04); border-radius:12px; padding:1rem; }}
    footer {{ text-align:center; padding:1rem; color:#666; font-size:0.85rem; }}
    .badge {{ display:inline-block; background:{secondary}; color:#fff; padding:0.2rem 0.5rem; border-radius:6px; font-size:0.75rem; }}
  </style>
</head>
<body>
  <header>
    <span class="badge">preview</span>
    <h1>{title}</h1>
    <p>{desc}</p>
  </header>
  <nav>{nav_html}</nav>
  <div class="wrap">
    <main>
      <h2>Latest posts</h2>
      {body}
    </main>
    {aside}
  </div>
  <footer>Static structure preview · not the live Blogger runtime · BloggerEasy</footer>
</body>
</html>
"""


def write_preview_html(structure: dict, out_path: Path) -> Path:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(structure_to_preview_html(structure), encoding="utf-8")
    return out_path
