"""One-command product path: input → importable theme + guide + evidence.

Issue #17 asks for a single, polished path that takes a screenshot/HTML/URL
and produces an importable Blogger theme *plus* a human-readable guide and a
machine-readable evidence manifest — all from one call. This module wires the
existing SDK generators into a self-contained output bundle:

    <out_dir>/
      theme.xml            # importable Blogger theme
      preview.html         # static structure preview (open in a browser)
      GUIDE.md             # step-by-step import guide
      evidence.json        # manifest: inputs, outputs, checksums, validation

The bundle is deterministic given the same inputs, so it doubles as PR
evidence (validation result + file checksums are recorded).
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from bloggereasy import __version__
from bloggereasy.integrations.sdk import (
    generate_from_html,
    generate_from_image,
    generate_from_url,
)
from bloggereasy.theme.preview import write_preview_html

BUNDLE_VERSION = "bloggereasy.bundle.v1"

_SOURCE_MODES = ("html", "url", "image")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    digest.update(path.read_bytes())
    return digest.hexdigest()


def _render_guide(structure: dict, *, source: str, source_ref: str, template: str, validation: dict) -> str:
    """Human-readable Markdown import guide bundled next to the theme."""
    title = str(structure.get("title") or "My Blog")
    layout = str(structure.get("layout") or "single-column")
    colors = structure.get("colors") or {}
    ok = "passed" if validation.get("ok") else "needs review"
    def _fmt(value: object) -> str:
        if isinstance(value, (list, tuple)):
            return ", ".join(f"`{v}`" for v in value)
        return f"`{value}`"

    color_rows = "\n".join(
        f"| {name} | {_fmt(value)} |"
        for name, value in colors.items()
    ) or "| (defaults) | — |"
    return f"""# BloggerEasy import guide — {title}

Generated by BloggerEasy {__version__} ({BUNDLE_VERSION}).

## What is in this bundle

| File | Purpose |
| --- | --- |
| `theme.xml` | Importable Blogger theme (upload this) |
| `preview.html` | Static preview of the layout — open in any browser |
| `GUIDE.md` | This guide |
| `evidence.json` | Machine-readable manifest (inputs, checksums, validation) |

## Source

- **Mode:** `{source}`
- **Reference:** `{source_ref}`
- **Template:** `{template}`
- **Layout:** `{layout}`
- **Validation:** **{ok}**

## Detected colors

| Role | Value |
| --- | --- |
{color_rows}

## Import into Blogger

1. Open [Blogger](https://www.blogger.com/) → your blog → **Theme**.
2. Click **⋮** → **Backup** to save your current theme first.
3. Click **⋮** → **Restore**, then upload `theme.xml` from this bundle.
4. Confirm — the layout, CSS skin, and widgets apply.
5. Preview the live blog and fine-tune under **Theme → Customize** if needed.

## Verify before uploading

```bash
bloggereasy validate -f theme.xml
```

A green `"ok": true` means the theme passed structural checks and is safe to
restore in Blogger.
"""


def generate_bundle(
    source_ref: str,
    out_dir: Path,
    *,
    source: str = "html",
    template: str = "simple",
    title: str = "My Blog",
) -> dict:
    """Produce a complete, importable theme bundle in ``out_dir``.

    ``source`` selects the input mode: ``html`` (local file), ``url`` (public
    page), or ``image`` (design screenshot). ``source_ref`` is the file path or
    URL for that mode.

    Returns a manifest dict (also written to ``evidence.json``) describing the
    inputs, generated files, checksums, and validation result.
    """
    if source not in _SOURCE_MODES:
        raise ValueError(f"Unknown source '{source}'. Expected one of {_SOURCE_MODES}.")

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    theme_path = out_dir / "theme.xml"

    if source == "html":
        result = generate_from_html(Path(source_ref), theme_path, template=template)
    elif source == "url":
        result = generate_from_url(source_ref, theme_path, template=template, cache_dir=out_dir)
    else:  # image
        image_template = template if template != "simple" else "from-image"
        result = generate_from_image(Path(source_ref), theme_path, title=title, template=image_template)

    structure = result["structure"]
    validation = result["validation"]

    preview_path = out_dir / "preview.html"
    write_preview_html(structure, preview_path)

    guide_path = out_dir / "GUIDE.md"
    guide_path.write_text(
        _render_guide(
            structure,
            source=source,
            source_ref=source_ref,
            template=result.get("template", template),
            validation=validation,
        ),
        encoding="utf-8",
    )

    files = {
        "theme": theme_path,
        "preview": preview_path,
        "guide": guide_path,
    }
    checksums = {name: _sha256(path) for name, path in files.items()}

    manifest = {
        "bundle_version": BUNDLE_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": source,
        "source_ref": source_ref,
        "template": result.get("template", template),
        "title": str(structure.get("title") or title),
        "layout": structure.get("layout"),
        "colors": structure.get("colors") or {},
        "validation": validation,
        "files": {name: str(path) for name, path in files.items()},
        "checksums": checksums,
        "import_hint": result.get("import_hint", "Blogger → Theme → Backup/Restore → Upload XML"),
    }

    evidence_path = out_dir / "evidence.json"
    evidence_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    manifest["files"]["evidence"] = str(evidence_path)

    return manifest
